<?php

namespace App\Filament\Resources;

use App\Filament\Resources\EmployeeResource\Pages;
use App\Filament\Resources\EmployeeResource\RelationManagers;
use App\Models\Account;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use TomatoPHP\FilamentAccounts\Filament\Resources\AccountResource;

class EmployeeResource extends AccountResource
{
    protected static ?string $model = Account::class;

    protected static ?string $navigationIcon = 'bx-male-female';

    public static function getNavigationLabel(): string
    {
        return "Employees";
    }

    public static function getPluralLabel(): ?string
    {
        return "Employees";
    }

    public static function getLabel(): ?string
    {
        return "Employee";
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->where('type', 'account'); // TODO: Change the autogenerated stub
    }


    public static function getPages(): array
    {
        return [
            'index' => Pages\ManageEmployees::route('/'),
        ];
    }
}
