<?php

namespace App\Filament\Resources;

use App\Filament\Pages\Dashboard;
use App\Filament\Resources\LeadResource\Pages;
use App\Filament\Resources\LeadResource\RelationManagers;
use App\Models\Account;
use Filament\Actions\Action;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use TomatoPHP\FilamentAccounts\Filament\Resources\AccountResource;
use TomatoPHP\FilamentSaasPanel\Filament\Resources\TeamResource\Actions\TeamTableAction;

class LeadResource extends AccountResource
{
    protected static ?string $model = Account::class;


    protected static ?string $navigationIcon = 'bxs-group';

    public static function getNavigationLabel(): string
    {
        return "Leads";
    }

    public static function getPluralLabel(): ?string
    {
        return "Leads";
    }

    public static function getLabel(): ?string
    {
        return "Lead";
    }

    public static function form(Form $form): Form
    {
        return $form->schema([
            AccountResource\Form\Components\Name::make(),
            AccountResource\Form\Components\Email::make(),
            AccountResource\Form\Components\Phone::make(),
        ]); // TODO: Change the autogenerated stub
    }

    public static function table(Table $table): Table
    {
        return parent::table($table)->actions([
            Tables\Actions\Action::make('view')
                ->tooltip('View')
                ->iconButton()
                ->color('info')
                ->icon('heroicon-s-eye')
                ->url(fn($record) => Dashboard::getUrl() . '?search='.$record->phone),
            Tables\Actions\Action::make('customer')
                ->requiresConfirmation()
                ->tooltip('Convert to Customer')
                ->iconButton()
                ->color('success')
                ->icon('heroicon-s-check-circle')
                ->action(function (Account $record) {
                    $record->update(['type' => 'customer']);

                    Notification::make()
                        ->title('Success')
                        ->body('Data saved successfully!')
                        ->success()
                        ->send();
                }),
            TeamTableAction::make(),
            AccountResource\Table\Actions\EditAction::make(),
            AccountResource\Table\Actions\DeleteAction::make(),
        ]); // TODO: Change the autogenerated stub
    }


    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->where('type', 'lead'); // TODO: Change the autogenerated stub
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ManageLeads::route('/'),
        ];
    }
}
